"""empty message

Revision ID: 6876deefe1c1
Revises: 92024345b909
Create Date: 2024-06-06 03:00:04.708908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6876deefe1c1'
down_revision = '92024345b909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_planet', sa.Integer(), nullable=True))
        batch_op.drop_constraint('person_homeworld_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['home_planet'], ['id'])
        batch_op.drop_column('homeworld')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('person_homeworld_fkey', 'planet', ['homeworld'], ['id'])
        batch_op.drop_column('home_planet')

    # ### end Alembic commands ###
