"""empty message

Revision ID: 68f5f8a390b6
Revises: b32089915c3f
Create Date: 2024-06-08 01:48:21.974436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f5f8a390b6'
down_revision = 'b32089915c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_planet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'planet', ['favorite_planet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite_planet_id')

    # ### end Alembic commands ###
