"""empty message

Revision ID: b32089915c3f
Revises: 907aac680e8c
Create Date: 2024-06-08 01:41:59.231188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32089915c3f'
down_revision = '907aac680e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_person_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'person', ['favorite_person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite_person_id')

    # ### end Alembic commands ###
